# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/common/common.proto\x12\x06\x63ommon\"\xc1\x01\n\rCommonReqInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x10\n\x08robot_id\x18\x06 \x01(\t\x12\x12\n\nrobot_type\x18\x07 \x01(\t\x12\x14\n\x0cservice_code\x18\x08 \x01(\t\x12\x0b\n\x03seq\x18\t \x01(\t\x12\x11\n\troot_guid\x18\n \x01(\t\"~\n\x0f\x43ommonReqHeader\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x10\n\x08robot_id\x18\x06 \x01(\t\x12\x12\n\nrobot_type\x18\x07 \x01(\t\x12\x14\n\x0cservice_code\x18\x08 \x01(\t\x12\x0b\n\x03seq\x18\t \x01(\t\"F\n\rCommonRspInfo\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x12\n\nerr_detail\x18\x03 \x01(\t\"/\n\x05\x45xtra\x12\x12\n\nextra_type\x18\x01 \x01(\t\x12\x12\n\nextra_body\x18\x02 \x01(\t\"\xc3\x01\n\x0e\x43ommonDataBody\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x30\n\x05param\x18\x02 \x03(\x0b\x32!.common.CommonDataBody.ParamEntry\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x12\n\ntime_stamp\x18\x04 \x01(\x03\x12\x1c\n\x05\x65xtra\x18\x05 \x01(\x0b\x32\r.common.Extra\x1a,\n\nParamEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONDATABODY_PARAMENTRY._options = None
  _COMMONDATABODY_PARAMENTRY._serialized_options = b'8\001'
  _globals['_COMMONREQINFO']._serialized_start=36
  _globals['_COMMONREQINFO']._serialized_end=229
  _globals['_COMMONREQHEADER']._serialized_start=231
  _globals['_COMMONREQHEADER']._serialized_end=357
  _globals['_COMMONRSPINFO']._serialized_start=359
  _globals['_COMMONRSPINFO']._serialized_end=429
  _globals['_EXTRA']._serialized_start=431
  _globals['_EXTRA']._serialized_end=478
  _globals['_COMMONDATABODY']._serialized_start=481
  _globals['_COMMONDATABODY']._serialized_end=676
  _globals['_COMMONDATABODY_PARAMENTRY']._serialized_start=632
  _globals['_COMMONDATABODY_PARAMENTRY']._serialized_end=676
# @@protoc_insertion_point(module_scope)
