# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import robotskill_pb2 as api_dot_robotskill__pb2


class RobotSkillServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableSkill = channel.unary_unary(
                '/robotmind.RobotSkillService/EnableSkill',
                request_serializer=api_dot_robotskill__pb2.EnableSkillRequest.SerializeToString,
                response_deserializer=api_dot_robotskill__pb2.EnableSkillResponse.FromString,
                )
        self.HandleAction = channel.unary_unary(
                '/robotmind.RobotSkillService/HandleAction',
                request_serializer=api_dot_robotskill__pb2.ActionRequest.SerializeToString,
                response_deserializer=api_dot_robotskill__pb2.ActionResponse.FromString,
                )


class RobotSkillServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnableSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotSkillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableSkill,
                    request_deserializer=api_dot_robotskill__pb2.EnableSkillRequest.FromString,
                    response_serializer=api_dot_robotskill__pb2.EnableSkillResponse.SerializeToString,
            ),
            'HandleAction': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleAction,
                    request_deserializer=api_dot_robotskill__pb2.ActionRequest.FromString,
                    response_serializer=api_dot_robotskill__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotmind.RobotSkillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotSkillService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnableSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotmind.RobotSkillService/EnableSkill',
            api_dot_robotskill__pb2.EnableSkillRequest.SerializeToString,
            api_dot_robotskill__pb2.EnableSkillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HandleAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotmind.RobotSkillService/HandleAction',
            api_dot_robotskill__pb2.ActionRequest.SerializeToString,
            api_dot_robotskill__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
