# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/robotskill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import common_pb2 as api_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/robotskill.proto\x12\trobotmind\x1a\x17\x61pi/common/common.proto\"\x9c\x01\n\x12\x45nableSkillRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x0f\n\x07\x61\x62ility\x18\x02 \x01(\x08\x12\r\n\x05param\x18\x03 \x01(\t\x12\x10\n\x08sub_addr\x18\x04 \x01(\t\x12\x10\n\x08sub_name\x18\x05 \x01(\t\x12\x12\n\nextra_type\x18\x06 \x01(\t\"V\n\x13\x45nableSkillResponse\x12/\n\x10\x63ommon_resp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12\x0e\n\x06result\x18\x02 \x01(\t\"k\n\rActionRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05param\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"O\n\x0e\x41\x63tionResponse\x12/\n\x10\x63ommon_resp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xaa\x01\n\x11RobotSkillService\x12N\n\x0b\x45nableSkill\x12\x1d.robotmind.EnableSkillRequest\x1a\x1e.robotmind.EnableSkillResponse\"\x00\x12\x45\n\x0cHandleAction\x12\x18.robotmind.ActionRequest\x1a\x19.robotmind.ActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.robotskill_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENABLESKILLREQUEST']._serialized_start=61
  _globals['_ENABLESKILLREQUEST']._serialized_end=217
  _globals['_ENABLESKILLRESPONSE']._serialized_start=219
  _globals['_ENABLESKILLRESPONSE']._serialized_end=305
  _globals['_ACTIONREQUEST']._serialized_start=307
  _globals['_ACTIONREQUEST']._serialized_end=414
  _globals['_ACTIONRESPONSE']._serialized_start=416
  _globals['_ACTIONRESPONSE']._serialized_end=495
  _globals['_ROBOTSKILLSERVICE']._serialized_start=498
  _globals['_ROBOTSKILLSERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
